reviews:
  auto_review: true
  language: ko      # 한국어로 리뷰
  review_comments: detailed
  coverage_requirements:
    min_coverage: 70

lint:
  enabled: true
  tools:
    - eslint
    - prettier

tasks:
  auto_create: true
